apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: website-application-green
  namespace: devopspoc
  labels:
    name: website-application
    service: website-application-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: website-application
      type: frontend
  template:
    metadata:
      labels:
        name: website-application
        type: frontend
        version: "1"
        deploymentType: GREEN
    spec:
      containers:
      - name: website-application
        image: nisumpk/website_application
        ports:
        - containerPort: 9001
        env:
        - name: SERVER_PORT
          value: -Dserver.port=9001
        - name: DISCOVERY_SERVER_URL
          value: "-Deureka.client.serviceUrl.defaultZone=http://discovery-server-service:7001/eureka/"
        - name: ADMIN_APPLICATION_URL
          value: -Dadmin.application.url=http://216.218.200.252/admin/companies
        - name: NEWS_APPLICATION_URL
          value: -Dnews.application.url=http://216.218.200.252/news/twitter
        command: ["java"]
        args: ["$(SERVER_PORT)", "$(ADMIN_APPLICATION_URL)", "$(NEWS_APPLICATION_URL)", "$(DISCOVERY_SERVER_URL)", "-Deureka.instance.preferIpAddress=true", "-Deureka.instance.ipAddress=website-application-service", "-jar", "/usr/src/website-application-SNAPSHOT.jar"]
