apiVersion: v1
kind: Service
metadata:
  name: website-application-service
  namespace: default
  labels:
    name: website-application-service
spec:
  type: NodePort
  ports:
  - port: 9001
    nodePort: 30006
    targetPort: 9001
    protocol: TCP

  selector:
    name: website-application
    deploymentType: BLUE
