apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: canary-server-gateway
  namespace: canary
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: website-application-virtualservice
  namespace: canary
spec:
  hosts:
  - "*"
  gateways:
  - canary-server-gateway
  http:
  - route:
    - destination:
        host: website-application
        port:
          number: 9001
        subset: website-application-v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: proxy-server-dr
  namespace: canary
spec:
  host: website-application
  subsets:
  - name: website-application-v1
    labels:
      version: website-application-v1
